var foodPlaces = [
 {"name": "Tim Hortons", "places": ["DC", "SLC", "ML","SCH","UWP"]},
 {"name": "Bon Appetit", "places": ["DC"]},
 {"name": "Browsers Cafe", "places": ["DP"]},
 {"name": "ML’s Coffee Shop", "places": ["ML"]},
 {"name": "Brubakers", "places": ["SLC"]},
 {"name": "Subway", "places": ["SLC"]},
 {"name": "CEIT Cafe", "places": ["EIT"]},
 {"name": "Eye Opener Cafe", "places": ["OPT"]},
 {"name": "Williams Fresh Cafe", "places": ["EV3"]},
 {"name": "Liquid Assets Cafe", "places": ["HH"]},
 {"name": "South Side Marketplace", "places": ["SCH"]},
 {"name": "Mudie’s", "places": ["V1"]},
 {"name": "PAS Lounge", "places": ["PAS"]},
 {"name": "FRSH", "places": ["AHS"]},
 {"name": "Pastry Plus", "places": ["TC","NH"]},
 {"name": "REVelation", "places": ["REV"]},
 {"name": "University Club", "places": ["UC"]},
 {"name": "UW Food Services Administrative Office", "places": ["EC3"]},
 {"name": "H3 Cafe", "places": ["HH"]},
 {"name": "Starbucks", "places": ["STC","BMH","AHS"]},
 {"name": "The Bombshelter Pub", "places": ["SLC"]},
 {"name": "Pastry Plus", "places": ["TC","NH"]},
 {"name": "The Dispensary", "places": ["PHR"]},
 {"name": "International News", "places": ["SLC"]},
 {"name": "Wasabi Sushi", "places": ["SLC"]},
 {"name": "Campus Bubble", "places": ["SLC"]},
 {"name": "Graduate House", "places": ["Graduate House"]},
 {"name": "Watson's Eatery", "places": ["STP"]},
 {"name": "Watson's Mug", "places": ["STP"]}]